#pragma once
// fast_agent_ingest.hpp — C++ wrapper around the fast-agent-ingest C ABI.
//
// The C header (fast_agent_ingest.h) is auto-generated by cbindgen.
// Run: just generate-headers
//
// Usage:
//   fai::Converter conv;
//   auto result = conv.convert("<html>...</html>");
//   std::cout << result.markdown << "\n";

#include <string>
#include <optional>
#include <stdexcept>

// Include the cbindgen-generated C header.
// Build the Rust library first: cargo build --package fast-agent-ingest-c-ffi --release
extern "C" {
#include "fast_agent_ingest.h"
}

namespace fai {

/// Options controlling HTML → Markdown conversion.
struct ConversionOptions {
    bool extract_main_content = true;
    bool include_images       = true;
    bool include_links        = true;
};

/// Result of a conversion.
struct ConversionResult {
    std::string            markdown;
    std::optional<std::string> title;
    std::optional<std::string> description;
};

/// Stateless converter. Thread-safe — all state lives in the Rust library.
class Converter {
public:
    /// Convert HTML to Markdown.
    ConversionResult convert(
        const std::string&     html,
        const ConversionOptions& opts = {}) const
    {
        FaiOptions c_opts{
            .extract_main_content = static_cast<uint8_t>(opts.extract_main_content ? 1 : 0),
            .include_images       = static_cast<uint8_t>(opts.include_images       ? 1 : 0),
            .include_links        = static_cast<uint8_t>(opts.include_links        ? 1 : 0),
        };

        FaiResult raw = fai_convert(html.c_str(), &c_opts);

        ConversionResult result;
        if (raw.markdown) result.markdown    = raw.markdown;
        if (raw.title)    result.title       = raw.title;
        if (raw.description) result.description = raw.description;

        fai_free_result(raw);
        return result;
    }
};

} // namespace fai
